Numpy arrays

python lists and arrays are different. 


In [1]:
my_list = [1, 2, 3]
print(my_list)


[1, 2, 3]


In [2]:
import numpy as np
convertedArrayfromlist = np.array(my_list)
print(convertedArrayfromlist)


[1 2 3]


In [3]:
print(convertedArrayfromlist)

[1 2 3]


In [4]:
my_2d_list = [[1,2, 3], [4,5,6]]
convertedArray = np.array(my_2d_list)
print(convertedArray)

[[1 2 3]
 [4 5 6]]


# **Creating Arrays** #


## Easy way 



In [8]:
created_array = np.arange(0, 10)
print(created_array)

[0 1 2 3 4 5 6 7 8 9]


Adding stepsize too


In [10]:
add_step_size  = np.arange(0, 20, 2)
print(add_step_size)

[ 0  2  4  6  8 10 12 14 16 18]


In [11]:
np.zeros(3)

array([0., 0., 0.])

In [18]:
## To create 2d matrix use a tuple to define it ##


In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [17]:
np.ones((5,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

### linspace divides the points bw two given points

In [21]:
np.linspace(0, 10, 5)


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [26]:
np.linspace(0,1 , 50)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

### Creating Identity matrix

In [31]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 1. np.random.rand
### Description: Generates random numbers from a uniform distribution in the range [0, 1).
### Range: Values are always between 0 (inclusive) and 1 (exclusive).
### Use Case: When you need random numbers evenly distributed within a specific range.

In [27]:
np.random.rand(5)

array([0.65412421, 0.47802256, 0.15216513, 0.43276941, 0.46512497])

In [32]:
np.random.rand(5,3)

array([[0.0746328 , 0.66444652, 0.41266295],
       [0.67997763, 0.59635678, 0.39502351],
       [0.89426837, 0.53941477, 0.62296513],
       [0.59313774, 0.63416663, 0.26263795],
       [0.14587643, 0.91550947, 0.94565097]])

## 2. np.random.randn
### Description: Generates random numbers from a standard normal distribution (Gaussian distribution) with:
### Mean (μ) = 0
### Standard deviation (σ) = 1
### Range: Theoretically, values can range from -∞ to +∞, but most values will be within -3σ to +3σ (about 99.7% of values fall in this range).
### Use Case: When you need random numbers with a bell-curve (normal distribution) for statistical or machine-learning tasks.


In [34]:
np.random.randn(4)


array([ 0.01665982, -1.19348581,  0.49474378, -1.84519527])

In [35]:
np.random.randn(5,5)

array([[-1.00910353, -1.26439116,  0.40564579, -0.45354295,  1.61926948],
       [ 1.08205029,  0.49738896,  0.69945677,  0.24792002,  0.66226109],
       [ 2.99836045, -0.8363237 ,  0.55635856,  0.89517739, -0.59225298],
       [-0.05540861,  1.39154646, -1.55048819, -1.260096  ,  0.1687968 ],
       [ 0.81057845,  0.26097195,  0.17822995,  1.44087731, -0.32069167]])

In [38]:
np.random.randint(3, 100)

15

In [39]:
np.random.randint(4, 500, 10)

array([460, 491, 221, 422, 194, 382,  13, 427, 474, 470])

### Reshaping arrays and more methods

In [44]:
random_array  = np.random.randint(0,500, 50)
print(random_array)
                                 

[379 422 402 382 489 380 389 210 493 349 363  64 327 166 274 357 418 474
  22  40 419 494 107 473 478 316  29 274 193  52 362  54 442  22 450 251
 278 109 465 300 215 195 317 103 379 134 191 215 350 256]


In [46]:
random_array.reshape(10,5)

array([[379, 422, 402, 382, 489],
       [380, 389, 210, 493, 349],
       [363,  64, 327, 166, 274],
       [357, 418, 474,  22,  40],
       [419, 494, 107, 473, 478],
       [316,  29, 274, 193,  52],
       [362,  54, 442,  22, 450],
       [251, 278, 109, 465, 300],
       [215, 195, 317, 103, 379],
       [134, 191, 215, 350, 256]])

In [47]:
random_array.shape


(50,)

In [48]:
random_array.dtype


dtype('int64')

In [54]:
type_array = np.random.randint(1,10, 4)
print(type_array)

[5 9 6 7]


In [53]:
type_array.dtype


dtype('int64')